name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Use the Node.js version specified in your project

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint

      # Add other steps as needed for your specific project, like running tests, building, or deploying

      - name: Build
        run: npm run build

      # Add other steps for deployment, if applicable
